Imports System
Imports System.Collections.Generic
Imports System.Data
Imports System.Data.Entity
Imports System.Linq
Imports System.Threading.Tasks
Imports System.Net
Imports System.Web
Imports System.Web.Mvc
Imports Reference.EIM.Domain

Namespace _2013_REF_EIM
    Public Class AddressController
        Inherits System.Web.Mvc.Controller

        'Default context that was generated by the scaffolding, replace wtih a constructor with the list of defined dependencies
        'Private db As New genContext

        Private _repository As Reference.EIM.Repository.IRepository

        Sub New(repository As Reference.EIM.Repository.IRepository)
            If repository Is Nothing Then Throw New ArgumentNullException("repository")
            _repository = repository
        End Sub

        ' GET: /Contact/
        'Async Function Index() As Task(Of ActionResult)
        '     Return View(Await db.Contacts.ToListAsync())
        'end function
        Function Index() As ActionResult
            'when the async controller option is checked it puts async on the controller as well as the repositroy get.
            'this level of async EF is in 6, however oracle doesn't support 6 or async
            Return View(_repository.GetQuery(Of Address)().Take(25).ToList)
        End Function

    End Class
End Namespace
