'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'	This template was modified to provide comments for the class and the entity and to add data annontation validation attributes to the properties as necessary.
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

	''' <summary>
	''' This is the short summary for the entity.
	''' </summary>
	''' <remarks>This is the long desc for the entity.</remarks>
Partial Public Class Address
	''' <summary>
	''' The Id field for the entity
	''' </summary>
	''' <remarks>This is a long description that hsould be populated with something meaningful.</remarks>
	<Required(ErrorMessage:="address ID is required.")>
    Public Property addressID As Integer 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="Street1 cannot be longer than 50 characters.")>
    Public Property Street1 As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="Street2 cannot be longer than 50 characters.")>
    Public Property Street2 As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="City cannot be longer than 50 characters.")>
    Public Property City As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="State Province cannot be longer than 50 characters.")>
    Public Property StateProvince As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="Country Region cannot be longer than 50 characters.")>
    Public Property CountryRegion As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<StringLengthAttribute(50, ErrorMessage:="Postal Code cannot be longer than 50 characters.")>
    Public Property PostalCode As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Address Type is required.")>
	<StringLengthAttribute(50, ErrorMessage:="Address Type cannot be longer than 50 characters.")>
    Public Property AddressType As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Contact ID is required.")>
    Public Property ContactID As Integer 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
	<Required(ErrorMessage:="Modified Date is required.")>
    Public Property ModifiedDate As Date 'simple property

	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Overridable Property Contact As Contact ' navigation property

End Class
