'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'	This template was modified to provide comments for the class and the entity and to add data annontation validation attributes to the properties as necessary.
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
Partial Public Class Contact
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(ErrorMessage:="Contact ID is required.")> <Display(Name:="Contact Id")>
 Public Property ContactID As Integer 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(ErrorMessage:="First Name is required.")>
    <StringLengthAttribute(50, ErrorMessage:="First Name cannot be longer than 50 characters.")> <Display(Name:="First Namme")>
 Public Property FirstName As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(ErrorMessage:="Last Name is required.")>
    <StringLengthAttribute(50, ErrorMessage:="Last Name cannot be longer than 50 characters.")> <Display(Name:="Last Name")>
 Public Property LastName As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <StringLengthAttribute(50, ErrorMessage:="Title cannot be longer than 50 characters.")> <Display(Name:="Title")>
    Public Property Title As String 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(ErrorMessage:="Add Date is required.")> <Display(Name:="Add Date")>
 Public Property AddDate As Date 'simple property
	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    <Required(ErrorMessage:="Modified Date is required.")> <Display(Name:="Modified Date")>
    Public Property ModifiedDate As Date 'simple property

	''' <summary>
	''' #TODO Populate Model Descriptions
	''' </summary>
	''' <remarks>#TODO Populate Model Descriptions</remarks>
    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address) ' navigation property

End Class
