'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Data.Mapping.EntityViewGenerationAttribute(GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets639304B0F38D564A3117166F0C4862A005355F0B55304F0E2C4CE0DA2D77CB71))> 

Namespace Edm_EntityMappingGeneratedViews
    
    '''<Summary>
    '''The type contains views for EntitySets and AssociationSets that were generated at design time.
    '''</Summary>
    Public NotInheritable Class ViewsForBaseEntitySets639304B0F38D564A3117166F0C4862A005355F0B55304F0E2C4CE0DA2D77CB71
        Inherits System.Data.Mapping.EntityViewContainer
        
        '''<Summary>
        '''The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        '''</Summary>
        Public Sub New()
            MyBase.New
            Me.EdmEntityContainerName = "SimpleEntities"
            Me.StoreEntityContainerName = "SimpleModelStoreContainer"
            Me.HashOverMappingClosure = "b8e3437ce2b0119b9ff5881c5001c77004717ed335bf90e52cd26847f340fb5e"
            Me.HashOverAllExtentViews = "6f00c1443838a558d5cdd568e18a1c3993c167da7ac004c8e90a74949fed8990"
            Me.ViewCount = 6
        End Sub
        
        '''<Summary>
        '''The method returns the view for the index given.
        '''</Summary>
        Protected Overrides Function GetViewAt(ByVal index As Integer) As System.Collections.Generic.KeyValuePair(Of String, String)
            If (index = 0) Then
                Return GetView0
            End If
            If (index = 1) Then
                Return GetView1
            End If
            If (index = 2) Then
                Return GetView2
            End If
            If (index = 3) Then
                Return GetView3
            End If
            If (index = 4) Then
                Return GetView4
            End If
            If (index = 5) Then
                Return GetView5
            End If
            Throw New System.IndexOutOfRangeException()
        End Function
        
        '''<Summary>
        '''return view for SimpleModelStoreContainer.Address
        '''</Summary>
        Private Function GetView0() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleModelStoreContainer.Address", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Address"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.Store.Address](T"& _ 
                    "1.Address_addressID, T1.Address_Street1, T1.Address_Street2, T1.Address_City, T1"& _ 
                    ".Address_StateProvince, T1.Address_CountryRegion, T1.Address_PostalCode, T1.Addr"& _ 
                    "ess_AddressType, T1.Address_ContactID, T1.Address_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "     SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.addressID AS Address_addressID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Stre"& _ 
                    "et1 AS Address_Street1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street2 AS Address_Street2, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"          "& _ 
                    "  T.City AS Address_City, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StateProvince AS Address_StateProvince"& _ 
                    ", "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CountryRegion AS Address_CountryRegion, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Postal"& _ 
                    "Code AS Address_PostalCode, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddressType AS Address_AddressType, "& _ 
                    ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ContactID AS Address_ContactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ModifiedDate AS "& _ 
                    "Address_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SimpleEntities."& _ 
                    "Addresses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SimpleModelStoreContainer.Contact
        '''</Summary>
        Private Function GetView1() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleModelStoreContainer.Contact", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Contact"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.Store.Contact](T"& _ 
                    "1.Contact_ContactID, T1.Contact_FirstName, T1.Contact_LastName, T1.Contact_Title"& _ 
                    ", T1.Contact_AddDate, T1.Contact_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "         T.ContactID AS Contact_ContactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.FirstName AS Contact_"& _ 
                    "FirstName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.LastName AS Contact_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Title A"& _ 
                    "S Contact_Title, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddDate AS Contact_AddDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Mod"& _ 
                    "ifiedDate AS Contact_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM Si"& _ 
                    "mpleEntities.Contacts AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SimpleEntities.Addresses
        '''</Summary>
        Private Function GetView2() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleEntities.Addresses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Addresses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.Address](T1.Ad"& _ 
                    "dress_addressID, T1.Address_Street1, T1.Address_Street2, T1.Address_City, T1.Add"& _ 
                    "ress_StateProvince, T1.Address_CountryRegion, T1.Address_PostalCode, T1.Address_"& _ 
                    "AddressType, T1.Address_ContactID, T1.Address_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"       "& _ 
                    " SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.addressID AS Address_addressID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street1 "& _ 
                    "AS Address_Street1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street2 AS Address_Street2, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T."& _ 
                    "City AS Address_City, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StateProvince AS Address_StateProvince, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
                    "            T.CountryRegion AS Address_CountryRegion, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.PostalCode"& _ 
                    " AS Address_PostalCode, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddressType AS Address_AddressType, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
                    "          T.ContactID AS Address_ContactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ModifiedDate AS Addr"& _ 
                    "ess_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SimpleModelStoreCon"& _ 
                    "tainer.Address AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SimpleEntities.Contacts
        '''</Summary>
        Private Function GetView3() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleEntities.Contacts", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Contacts"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.Contact](T1.Con"& _ 
                    "tact_ContactID, T1.Contact_FirstName, T1.Contact_LastName, T1.Contact_Title, T1."& _ 
                    "Contact_AddDate, T1.Contact_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
                    "    T.ContactID AS Contact_ContactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.FirstName AS Contact_First"& _ 
                    "Name, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.LastName AS Contact_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Title AS Con"& _ 
                    "tact_Title, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddDate AS Contact_AddDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Modified"& _ 
                    "Date AS Contact_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SimpleM"& _ 
                    "odelStoreContainer.Contact AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SimpleModelStoreContainer.vOfficeAddresses
        '''</Summary>
        Private Function GetView4() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleModelStoreContainer.vOfficeAddresses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing vOfficeAddresses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.Store.v"& _ 
                    "OfficeAddresses](T1.vOfficeAddresses_FirstName, T1.vOfficeAddresses_LastName, T1"& _ 
                    ".vOfficeAddresses_addressID, T1.vOfficeAddresses_Street1, T1.vOfficeAddresses_St"& _ 
                    "reet2, T1.vOfficeAddresses_City, T1.vOfficeAddresses_StateProvince, T1.vOfficeAd"& _ 
                    "dresses_CountryRegion, T1.vOfficeAddresses_PostalCode, T1.vOfficeAddresses_Addre"& _ 
                    "ssType, T1.vOfficeAddresses_ContactID, T1.vOfficeAddresses_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FR"& _ 
                    "OM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.FirstName AS vOfficeAddresses_FirstName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
                    "            T.LastName AS vOfficeAddresses_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.addressID A"& _ 
                    "S vOfficeAddresses_addressID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street1 AS vOfficeAddresses_Street"& _ 
                    "1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street2 AS vOfficeAddresses_Street2, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.City AS "& _ 
                    "vOfficeAddresses_City, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StateProvince AS vOfficeAddresses_StatePr"& _ 
                    "ovince, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CountryRegion AS vOfficeAddresses_CountryRegion, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
                    "       T.PostalCode AS vOfficeAddresses_PostalCode, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddressType "& _ 
                    "AS vOfficeAddresses_AddressType, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ContactID AS vOfficeAddresses_C"& _ 
                    "ontactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ModifiedDate AS vOfficeAddresses_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
                    "       True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SimpleEntities.vOfficeAddresses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) "& _ 
                    "AS T1")
        End Function
        
        '''<Summary>
        '''return view for SimpleEntities.vOfficeAddresses
        '''</Summary>
        Private Function GetView5() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SimpleEntities.vOfficeAddresses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing vOfficeAddresses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SimpleModel.vOffice"& _ 
                    "Address](T1.vOfficeAddress_FirstName, T1.vOfficeAddress_LastName, T1.vOfficeAddr"& _ 
                    "ess_addressID, T1.vOfficeAddress_Street1, T1.vOfficeAddress_Street2, T1.vOfficeA"& _ 
                    "ddress_City, T1.vOfficeAddress_StateProvince, T1.vOfficeAddress_CountryRegion, T"& _ 
                    "1.vOfficeAddress_PostalCode, T1.vOfficeAddress_AddressType, T1.vOfficeAddress_Co"& _ 
                    "ntactID, T1.vOfficeAddress_ModifiedDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"         "& _ 
                    "   T.FirstName AS vOfficeAddress_FirstName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.LastName AS vOfficeA"& _ 
                    "ddress_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.addressID AS vOfficeAddress_addressID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
                    "      T.Street1 AS vOfficeAddress_Street1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Street2 AS vOfficeAdd"& _ 
                    "ress_Street2, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.City AS vOfficeAddress_City, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.State"& _ 
                    "Province AS vOfficeAddress_StateProvince, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CountryRegion AS vOffi"& _ 
                    "ceAddress_CountryRegion, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.PostalCode AS vOfficeAddress_PostalCode"& _ 
                    ", "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.AddressType AS vOfficeAddress_AddressType, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Con"& _ 
                    "tactID AS vOfficeAddress_ContactID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.ModifiedDate AS vOfficeAddre"& _ 
                    "ss_ModifiedDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SimpleModelStoreCont"& _ 
                    "ainer.vOfficeAddresses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
    End Class
End Namespace
